### ISSUE TITLE
problem with Segment Moudel in the source code

### ISSUE THREAD

**Issue by appdroids** [hamedhemati/Tacotron-2-Persian#1]
hi, i cant download the mozilla voice commons in persian, all links are expired and the segment moudel does not finded by source code , can you send me a complit source please ? it is very important for me ... my telegram id @mohammad_ebrz

**Comment by hamedhemati** [comment]
Hi. I checked the links and all of them work for me. For Mozilla Common Voice you need to select Persian on the right side of the page and enter your email to download. Regarding the `segment` module, you can simply install the package with `pip install segment`. There might be a few other common modules that you need to install with pip/conda depending on your Python version/environment.
