### ISSUE TITLE
Problem in generate.sh

### ISSUE THREAD

**Issue by shamsnaamir** [hamedhemati/Tacotron-2-Persian#12]
Hello @hamedhemati 
When I tried to run the `generate.sh` file. I faced this error:

```
/usr/bin/python3: Error while finding module specification for 'TTS.acoustic_model.tacotron2.generate' (ModuleNotFoundError: No module named 'TTS.acoustic_model')
```

After that, I changed `generate.sh` like the below, to call `generate.py`:

```
#! /bin/bash

# get path to config file
full_path=$0
CONFIG_PATH=$(dirname "$full_path")
echo $CONFIG_PATH


CHECKPOINT_ID="100"

SPEAKER=""
LANGUAGE="fa"

INP_TEXT="دلا نزدِ کسی بنشین که او از دل خبر دارد."

#tac2persian.train
#python -m TTS.acoustic_model.
python -m tac2persian.generate --tacotron_config_path="/content/drive/MyDrive/TTS/Tacotron-2-Persian/scripts/tacotron2persian_commonvoice_fa/config.yml" \
                               --wavernn_config_path="/content/drive/MyDrive/TTS/Tacotron-2-Persian/scripts/preprocess_commonvoice_fa/config.yml" \
                               --inp_text="سلام" --tacotron_checkpoint_path="/content/drive/MyDrive/TTS/Tacotron-2-Persian/outputs/commonvoice_fa/checkpoints/checkpoint_0K.pt"
                                                #--checkpoint_id="$CHECKPOINT_ID" \
                                                #--speaker="$SPEAKER" \
                                               # --language="$LANGUAGE" \
```

But there were some flags such as tactron_checkpoint_path and wavernn_checkpoint_path that I didn't know how to fill.
After some searching, I changed the file as upper. But after running the project there were some missing keys and values in the config.yml files. I've struggled a lot but I couldn't solve the problem.

I've would be very happy if you would help me to fix this problem.
thank you
regards

**Comment by shamsnaamir** [comment]
By the way, I am not using the demo version and I am training it with another dataset.
thank you

**Comment by sepehrmizani** [comment]
Hi
I have the same problem
thank you
regards

**Comment by hamedhemati** [comment]
Hi @shamsnaamir. Thanks for reporting the issue and sorry for the trouble. It seems like the generate shell is a wrong file. Could you please post the error here so that I can add the missing keys and fix the shell file?

**Comment by shamsnaamir** [comment]
Hello
When I run the original generate.py I get this error
```
/usr/bin/python3: Error while finding module specification for 'TTS.acoustic_model.tacotron2.generate' (ModuleNotFoundError: No module named 'TTS.acoustic_model')
```

**Comment by hamedhemati** [comment]
@shamsnaamir @sepehrmizani  I've updated the generate shell script. I also tested It locally and worked fine, I just had to replace `librosa` with `soundfile` since the last versions of `librosa` do not support outputting wav files anymore.

**Comment by shamsnaamir** [comment]
thanks a million
