### ISSUE TITLE
[Request] Make training process available in form of a notebook

### ISSUE THREAD

**Issue by prp-e** [hamedhemati/Tacotron-2-Persian#14]
Greetings Dear Hamed. 
I was looking for a reliable and stable Persian TTS software, and I found your repository here. Now, I open this issue to make a few requests.

1. Making training/inference process available in form of a colab notebook
2. A quick guide on dataset
3. A quick guide on _how to make an inference program for your TTS_

Regards.

**Comment by HamedHemati** [comment]
Hi @prp-e 

Sorry for my late response. Unfortunately, I will not be able to work on this repo for the next few months as I will be busy with other projects. However, I believe that it should not be very difficult to provide the notebooks by going through the readme and the scripts provided for training and inference.

If you have time later to create the notebooks and would like to share them, I would be happy to merge them in the repo via a PR from your side.

Best
