### ISSUE TITLE
how train and set dataset and set ./wav

### ISSUE THREAD

**Issue by aref3dx** [hamedhemati/Tacotron-2-Persian#15]
**Please provide a complete explanation of how to train** 
!sh /content/Tacotron-2-Persian/scripts/tacotron2persian_commonvoice_fa/train.sh

**in set dataset path** 
/content/Tacotron-2-Persian/scripts/tacotron2persian_commonvoice_fa/config.yml
datasets:
  commonvoice_fa:
    dataset_path: "PATH TO PRE-PROCESSED DATASET"
    max_mel_len: 1000
    train_metafile: "metadata_train.txt"
    eval_metafile: "metadata_train.txt"                      
    speakers_list: ["speaker_fa_0"]

**Please help me step to step for train**

**Comment by HamedHemati** [comment]
@aref3dx 
I have to close this issue since I'm archiving the repo. As the dataset might've changed, I recommend checking other up-to-date Persian TTS repositories. Good luck with your TTS journey! :)
