### ISSUE TITLE
Making Dataset

### ISSUE THREAD

**Issue by karim23657** [hamedhemati/Tacotron-2-Persian#16]
Hi , Could you please share the dataset you have created?

**Comment by Oct4Pie** [comment]
@karim23657 I saw you made a model for coqui. I have many datasets. Can you contact me on Telegram? 
Username: @minipi0

**Comment by HamedHemati** [comment]
@karim23657 @Oct4Pie 
I have to close this issue since I'm archiving the repo. Good luck with your TTS journey! :)
