### ISSUE TITLE
About using the tacotron2 for Persian langue

### ISSUE THREAD

**Issue by soheilpaper** [hamedhemati/Tacotron-2-Persian#2]
I have seen this project via [medium](https://medium.com/@hemati.hmd/persian-tts-with-tacotron-2-persian-18c39a52693c) and [GitHub site,](https://github.com/hamedhemati/Tacotron-2-Persian) which is using the tacotron2 for Persian language, but its codes are not completed and don't work, so I tried to combine those but [this](https://colab.research.google.com/github/So-AI-love/Tacotron-2-Persian/blob/master/notebooks/test_phonemizer.ipynb#scrollTo=ebj-hWRMSNtM) project and made [this](https://colab.research.google.com/github/So-AI-love/Tacotron-2-Persian/blob/master/notebooks/test_phonemizer.ipynb#scrollTo=ebj-hWRMSNtM) colab page.

So as I am a newbie with tacotron2, I asked here to understand better what can I do to make that codes to working for Persian language too.

Thanks for your consideration.

**Comment by hamedhemati** [comment]
Hi!
Sorry for my delayed reply. Unfortunately, I didn't receive any notification for this issue for some reason.
Regarding your question, I'm not sure if I understood it correctly, but if you just want to test a trained model you can use the available checkpoints downloadable from the link on the readme page (demo section):
https://github.com/hamedhemati/Tacotron-2-Persian#demo
By following the explanation you should be able to generate speech as mentioned.
Let me know if this doesn't help.
