### ISSUE TITLE
validate.tsv

### ISSUE THREAD

**Issue by AmirAliAslani** [hamedhemati/Tacotron-2-Persian#4]
I was making the metadata file (the first step) but it asked me about validate.tsv file.
From where I can find it?
@hamedhemati

**Comment by hamedhemati** [comment]
Hi, 
after downloading and extracting the CommonVoice Persian dataset zip file from [https://commonvoice.mozilla.org/en/datasets](MozillaCommonVoice),  there should be a subfolder `fa` in the created folder as below depending on the version XXX that you've downloaded:
`cv-corpus-XXX/fa/`
You can find the validate.tsv and other files under this directory.
Make sure that you've correctly set the `DATASET_PATH` variable in the bash script `scripts/preprocess/preprocess_commonvoice_fa.sh`  to the full path of the `.../fa` directory (which is considered as the dataset root) before running it.

**Comment by AmirAliAslani** [comment]
Hello thanks for your guide,
but when I unzipped the file I saw this :
![image](https://user-images.githubusercontent.com/79202220/115981281-c9e0b380-a5a7-11eb-9ad0-94d89aeec232.png)
There is no folder named fa, there is only a file with this name.

**Comment by hamedhemati** [comment]
Ok, now I see. The downloaded file is supposed to be a `.tar` file. Have you tried to extract it with some extraction tool that supports TAR format? 
For example 7-Zip: [https://www.7-zip.org/](https://www.7-zip.org/)
