### ISSUE TITLE
Error in processing.

### ISSUE THREAD

**Issue by AmirAliAslani** [hamedhemati/Tacotron-2-Persian#5]
Thank you for your guide for the .tar file.
But I've got another error:
![image](https://user-images.githubusercontent.com/79202220/116072447-583a5f80-a6a4-11eb-8c11-0bf0ad4e6e34.png)
![image](https://user-images.githubusercontent.com/79202220/116072478-62f4f480-a6a4-11eb-9bfb-7227a01d0ecb.png)
What should I do?

**Comment by mvardin** [comment]
Hi
Probably , you got this error in catch

` raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/home/mvardin/Tacotron-2-Persian/fa/clips/common_voice_fa_19039800.mp3': File contains data in an unknown format.
`

I'm working on it , if i get how to solve the issue , ill post here ;)
