### ISSUE TITLE
limiting line in prepocessing

### ISSUE THREAD

**Issue by MahdiEsrafili** [hamedhemati/Tacotron-2-Persian#8]
Hello. Thanks for you great work. 
I was following you instructions on how to train the model. In data preprocessing, after running:

```
sh scripts/preprocess/preprocess_commonvoice_fa.sh
```

I got only 20 lines in `metadata.txt`, after reading the code, I found out that in file `tac2persian/data_preprocessing/preprocess_commonvoice_fa.py`:

```
for itr, line in enumerate(lines[:20]):
```

you have limited the lines which causes the problem. What is this limiting for?
thanks you again.

**Comment by mvardin** [comment]
Hi
I think its for test or something else
You can remove [:20] and use it in unlimited

**Comment by MahdiEsrafili** [comment]
@mvardin  yes I did that and it was ok. thanks
