### ISSUE TITLE
About debugging the text-to-speech tacotron2 for Persian language (missed validated.tsv)

### ISSUE THREAD

**Issue by soheilpaper** [hamedhemati/Tacotron-2-Persian#9]
I am trying to debug one [text-to-speech tactron2 project in GitHub][1] for Persian language, and edited its google colaratorary page at [here][2], in the part of testing its demo part:

[enter image description here][3]

> To only test the model, I've provided a demo script folder that also
> contains the checkpoints for Tacotron and WaveRNN. Download the demo
> experiment zip from:
> https://drive.google.com/file/d/1wzlBGgROS76W4xOY1UpCZaW5zropyLVL/view?usp=sharing
> and unzip it under ./scripts/ folder. Similar to what explained in the
> Inference section, you just need to run:
> 
> sh scripts/demo/generate.sh Example outputs Below you see the
> generated mel-spectrogram and attention matrix for the setence:
> 
> Obviously, the quality of generated mel-spectrogram/audio is lower
> than those generated from a standard model trained on English or
> Japanese languages, which is mainly caused by the quality of the
> audios in the dataset.

So I have got the below error in the running the `!sh /content/Tacotron-2-Persian/scripts/preprocess_commonvoice_fa/preprocess_commonvoice_fa.sh` part of the [Google colab page][2]:

```
/content/Tacotron-2-Persian/scripts/preprocess_commonvoice_fa
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/Tacotron-2-Persian/tac2persian/data_preprocessing/preprocess_commonvoice_fa.py", line 111, in <module>
    preprocess(args.dataset_path, args.output_path, target_speakers, config, args.num_workers)
  File "/content/Tacotron-2-Persian/tac2persian/data_preprocessing/preprocess_commonvoice_fa.py", line 49, in preprocess
    with open(os.path.join(dataset_path, "validated.tsv"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/Tacotron-2-Persian/scripts/demo/validated.tsv'
```
Also, the content of `preprocess_commonvoice_fa.sh` file is shown below:

```
#! /bin/bash

# Get full path to the config file automatically
full_path=$0
CONFIG_PATH=$(dirname "$full_path")
echo $CONFIG_PATH


DATASET_PATH="PATH TO DATASET"
OUTPUT_PATH="PATH TO THE OUTPUT DIRECTORY"
NUM_WORKERS=5

python -m tac2persian.data_preprocessing.preprocess_commonvoice_fa --dataset_path="$DATASET_PATH" \
                                                                   --output_path="$OUTPUT_PATH" \

```

Also asked below:

https://stackoverflow.com/questions/69934192/about-debugging-the-text-to-speech-tacotron2-for-persian-language-missed-valida

Thanks.

  [1]: https://github.com/So-AI-love/Tacotron-2-Persian/
  [2]: https://colab.research.google.com/github/So-AI-love/Tacotron-2-Persian/blob/master/notebooks/test_phonemizer.ipynb
  [3]: https://i.stack.imgur.com/WPAlb.png

**Comment by hamedhemati** [comment]
Hi!
If you want to test the pre-trained model, you just need to follow the `Demo` section on the README page. First, download the demo files and then run `sh scripts/demo/generate.sh`. Dataset preprocessing step is needed only when you want to train the model and for that, you need to download the entire dataset which contains a `validated.tsv` file.
